### ISSUE TITLE
Autoencoder section has some erorrs with newer Keras 0.3

### ISSUE THREAD

**Issue by DSPTESTER** [snth/ctdeep#1]
# creating the autoencoder

from keras.models import Sequential
from keras.layers import containers
from keras.layers.core import Dense, Activation, AutoEncoder
ae = Sequential()
encoder = containers.Sequential()
encoder.add(Dense(input_dim=784, output_dim=512, init='uniform'))
encoder.add(Activation('sigmoid'))
decoder = containers.Sequential()
decoder.add(Dense(512, 784, init='uniform'))
decoder.add(Activation('sigmoid'))
ae.add(AutoEncoder(encoder=encoder, decoder=decoder,
                   output_reconstruction=True))
# creating the autoencoder

from keras.models import Sequential
from keras.layers import containers
from keras.layers.core import Dense, Activation, AutoEncoder
ae = Sequential()
encoder = containers.Sequential()
encoder.add(Dense(input_dim=784, output_dim=512, init='uniform'))
encoder.add(Activation('sigmoid'))
decoder = containers.Sequential()
decoder.add(Dense(512, 784, init='uniform'))
decoder.add(Activation('sigmoid'))
ae.add(AutoEncoder(encoder=encoder, decoder=decoder,
##                    output_reconstruction=True))

TypeError                                 Traceback (most recent call last)
<ipython-input-20-47f5179e0ff1> in <module>()
      8 encoder.add(Activation('sigmoid'))
      9 decoder = containers.Sequential()
---> 10 decoder.add(Dense(512, 784, init='uniform'))
     11 decoder.add(Activation('sigmoid'))
     12 ae.add(AutoEncoder(encoder=encoder, decoder=decoder,

TypeError: **init**() got multiple values for keyword argument 'init'

**Comment by snth** [comment]
Aha, I think they changed the signature of the Dense layers (and possibly other layers).

I encountered this before when I played around with it myself. That is why earlier on in the notebook I was specifying `input_dim` and `output_dim` explicitly

```
encoder.add(Dense(input_dim=784, output_dim=512, init='uniform'))
```

It appears I got lazy later on.

Try putting in `input_dim` and `output_dim` kwarg names where `input_dim` is the first parameter and `output_dim` is the second.

**Comment by DSPTESTER** [comment]
encoder.add(Dense(input_dim=784, output_dim=512))

## decoder.add(Dense(512, 784))

Fixes the issue but init is not there. Also I see more issue on, don't know if its related to the above. 
BTW - There in good autoencoder examples for Keras except yours !! Should  push yours it to Keras.git 

ae.compile(loss='mean_squared_error', optimizer='SGD')

## ae.compile(loss='mean_squared_error', optimizer='SGD')

AttributeError                            Traceback (most recent call last)
<ipython-input-32-c1c17a18e435> in <module>()
----> 1 ae.compile(loss='mean_squared_error', optimizer='SGD')

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/models.pyc in compile(self, optimizer, loss, class_mode, theano_mode)
    370         self.X_test = self.get_input(train=False)
    371 
--> 372         self.y_train = self.get_output(train=True)
    373         self.y_test = self.get_output(train=False)
    374 

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/layers/containers.pyc in get_output(self, train)
     80 
     81     def get_output(self, train=False):
---> 82         return self.layers[-1].get_output(train)
     83 
     84     def set_input(self):

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/layers/core.pyc in get_output(self, train)
    904             return self.encoder.get_output(train)
    905 
--> 906         return self.decoder.get_output(train)
    907 
    908     def get_config(self):

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/layers/containers.pyc in get_output(self, train)
     80 
     81     def get_output(self, train=False):
---> 82         return self.layers[-1].get_output(train)
     83 
     84     def set_input(self):

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/layers/core.pyc in get_output(self, train)
    524 
    525     def get_output(self, train=False):
--> 526         X = self.get_input(train)
    527         return self.activation(X)
    528 

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/layers/core.pyc in get_input(self, train)
    114     def get_input(self, train=False):
    115         if hasattr(self, 'previous'):
--> 116             return self.previous.get_output(train=train)
    117         elif hasattr(self, 'input'):
    118             return self.input

/usr/local/lib/python2.7/dist-packages/Keras-0.3.0-py2.7.egg/keras/layers/core.pyc in get_output(self, train)
    694     def get_output(self, train=False):
    695         X = self.get_input(train)
--> 696         output = self.activation(K.dot(X, self.W) + self.b)
    697         return output
    698 

AttributeError: 'Dense' object has no attribute 'W'

**Comment by snth** [comment]
Hi, I did a bit of work and the latest master now works for me on Keras 0.3. Do a git pull and see if that fixes your issues.

**Comment by DSPTESTER** [comment]
Thanks a lot !

**Comment by DSPTESTER** [comment]
closing
